apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-mall-route
  namespace: go-mall
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: "underscores_in_headers on"

spec:
  rules:
    - host: nginx.kubernetes-devops.cn
      http:
        paths:
          - path: /douyin/user
            pathType: ImplementationSpecific
            backend:
              service:
                name: users-api
                port:
                  number: 8001
