apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: go-mall
  labels:
    app: go-mall
    service: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-mall
      service: users
  template:
    metadata:
      labels:
        app: go-mall
        service: users
    spec:
      containers:
        - name: users-service
          image: swr.cn-south-1.myhuaweicloud.com/jjzzchtt/go-mall:latest
          command: ["/app/services/Users", "-f", "/app/etc/users.prod.yaml"]
          ports:
            - containerPort: 10001  # 主服务端口
            - containerPort: 11001  # 健康检查端口
          envFrom:
            - configMapRef:
                name: go-mall-env
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
          volumeMounts:
            - mountPath: /app/logs
              name: app-logs
          livenessProbe:
            httpGet:
              path: /health
              port: 11001
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 11001
            initialDelaySeconds: 5
          imagePullPolicy: IfNotPresent
      volumes:
        - name: app-logs
          hostPath:
            path: /app/logs

---
# users-service 的 Service
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: go-mall
spec:
  selector:
    app: go-mall
    service: users
  ports:
    - name: http
      port: 10001
      targetPort: 10001
      nodePort: 31001  # 按需修改
    - name: metrics
      port: 11001
      targetPort: 11001
      nodePort: 31101  # 按需修改
  type: NodePort
